version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/react-console-emulator
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Workaround for Puppeteer on Docker
          command: 'sh .circleci/puppeteer.sh'
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run unit tests
          command: npm run deptest
      - run:
          name: Generate test build
          command: npm run build
